### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by alejandropaciotti** [cmwalsh/express_rethink#1]
When i post to localhost:3000/login with the headers:

``` json
{
"email": "anyone@anywhere.com",
"id": 1 ,
"password":  "mypassword" ,
"username":  "myusername"
}
```

a message error reject:

``` shell
handled rejection ReferenceError: Promise is not defined
at Object.module.exports.authenticate (/home/user/samples/lib/auth.js:24:16)
    at /home/user/samples/routes/login.js:19:14
```

I think a library is missing in the package.json

**Comment by alejandropaciotti** [comment]
I solved the problem with:

``` shell
npm install bluebird --save
```

And added in auth.js

``` javascript
Promise var = require ("bluebird");
```
